version: '3'

services:
  mysql-database:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_HOST: ${{ secrets.DATABASE_HOST }}
      MYSQL_USER: ${{ secrets.DATABASE_USER }}
      MYSQL_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      MYSQL_DB: ${{ secrets.DATABASE_NAME }}

  python:
    build: .
    depends_on:
      - mysql-database
    environment:
      MYSQL_HOST: ${{ secrets.DATABASE_HOST }}
      MYSQL_USER: ${{ secrets.DATABASE_USER }}
      MYSQL_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      MYSQL_DB: ${{ secrets.DATABASE_NAME }}