version: '3'

services:
  mysql-database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_HOST: $${{ secrets.DATABASE_HOST }}
      MYSQL_USER: $${{ secrets.DATABASE_USER }}
      MYSQL_PASSWORD: $${{ secrets.DATABASE_PASSWORD }}
      MYSQL_DB: $${{ secrets.DATABASE_NAME }}

  python:
    build: .
    depends_on:
      - mysql-database
    environment:
      MYSQL_HOST: $${{ secrets.DATABASE_HOST }}
      MYSQL_USER: $${{ secrets.DATABASE_USER }}
      MYSQL_PASSWORD: $${{ secrets.DATABASE_PASSWORD }}
      MYSQL_DB: $${{ secrets.DATABASE_NAME }}