version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  add_new_data:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: ls
          command: ls -R
      - run:
          name: Update pip
          command: pip install --upgrade pip
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install requirements
          command: pip install -r requirements.txt
      - run:
          name: Run script
          command: python scripts/add_data_until_last_record.py

workflows:
  version: 2
  sample:
    jobs:
      - add_new_data:
          filters:
            branches:
              only:
                - main
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
          filters:
            branches:
              only:
                - main
