name: Mon Workflow

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code source
        uses: actions/checkout@v2
      - name: Installer Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Exécuter le script
        run: python add_data_until_last_record.py
