name: Mon Workflow

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Exécuter le script
        run: python add_data_until_last_record.py
