name: Docker Compose

on:
  schedule:
    - cron: '0 * * * *' # Planifiez le déclenchement de cette action toutes les heures

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Start Docker Compose
      run: docker-compose up -d
